org: unclegabi
app: serverless-react-app
service: serverless-sample
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"

functions:
  fetchTodos:
    handler: src/fetchTodos.handler
    events:
      - http:
          path: /
          method: get
  fetchTodo:
    handler: src/fetchTodo.handler
    events:
      - http:
          path: /{id}
          method: get
          cors: true

  addTodo:
    handler: src/addTodo.handler
    events:
      - http:
          path: /
          method: post
          cors: true
  updateTodo:
    handler: src/updateTodo.handler
    events:
      - http:
          path: /{id}
          method: put
          cors: true
  removeTodo:
    handler: src/removeTodo.handler
    events:
      - http:
          path: /{id}
          method: delete
          cors: true
